// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"context"

	"github.com/go-logr/logr"

	"github.com/liuerfire/boxpractice/internal/services"
	"github.com/liuerfire/boxpractice/pkg/store"
)

// Injectors from wire.go:

func InitAPIHandler(ctx context.Context, logger logr.Logger, sqlStore *store.SQLStore) (*API, error) {
	hospitalService := services.ProvideHospitalService(logger, sqlStore)
	employeeService := services.ProvideEmployeeService(logger, sqlStore)
	taskService := services.ProvideTaskService(logger, sqlStore)
	api := ProvideAPI(logger, hospitalService, employeeService, taskService)
	return api, nil
}
